---
- hosts: webserver
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: copy files
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
